### ISSUE TITLE
`async_add_job`, is deprecated and will be removed in Home Assistant 2025.4

### ISSUE THREAD

**Issue by kovacsla** [bob-tm/ha-openhab#1]
Detected that custom integration 'openhab' calls `async_add_job`, which is deprecated and will be removed in Home Assistant 2025.4; Please review https://developers.home-assistant.io/blog/2024/03/13/deprecate_add_run_job for replacement options at custom_components/openhab/__init__.py, line 56: hass.async_add_job(, please create a bug report at https://github.com/bob-tm/ha-openhab/issues

**Comment by bob-tm** [comment]
Please try master with all three fixes

**Comment by kovacsla** [comment]
Perfect it is working. All three fixes. 

I found two other mistiques (sorry):

  TEMP_CELSIUS was used from openhab, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead.
 
TEMP_FAHRENHEIT was used from openhab, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.FAHRENHEIT instead.

**Comment by bob-tm** [comment]
Fixed in master

**Comment by kovacsla** [comment]
Perfect "master" is working. All openhab errors disappeared in the log. Thx

**Comment by kovacsla** [comment]
Today I upgraded HACS from 1.34 => 2.0, then OpenHAB integration offered me to upgrade (I didn't notice that it's an older version than the one I have). I did it and the errors reappeared. I reset the "master" version to 0.5.9. The new version of HACS does not even let you install the "master" version. Could you put the above changes into a new version? Thx.  
![image](https://github.com/user-attachments/assets/68a3f3d7-be46-4b4e-8d64-9b124c52a665)
![image](https://github.com/user-attachments/assets/99845e69-f4f6-438f-ac86-7330c36f98e2)

**Comment by bob-tm** [comment]
0.6 is released

**Comment by kovacsla** [comment]
Perfect it is working. Thx
